import { workerScenario as generatedScenario } from "../generated/workerScenario.generated.ts";
import { createScenarioRuntime } from "./scenarioRuntime.ts";
export const defaultScenarioRuntime = createScenarioRuntime(generatedScenario);
export const {
  workerScenario,
  isSearchAgentTalk,
  isDeviceTalk,
  internalAttachmentId,
  internalIncomingCallId,
  internalFormId,
  lockedContentPassword,
  resolveTalkAttachment,
  albumPhotoIdsForMediaAttachment,
  messageTemplatesForBlock,
  talkBlockIdForRepeatDisplay,
  messagesForTalkBlocks,
  applyTalkInputAction,
  messagesForTalkOutputSteps,
  initialTalkTurnKey,
  nextTalkTurnKey,
  searchAgentTimelineForOutputs,
  initializeSearchAgentTalkState,
  talkTurnHash,
  scenarioMessageBlockId,
  talkInputBoundarySeq,
  initializeTalkState,
  restoredTalkHistoryMessages,
  synchronizeInitialTalkLastOtherMessageId,
  talkHistoryRepairAvailable,
  createInitialPlayerState,
  revealTalkMessages,
  reconcileScenarioState,
  appAvailable,
  contentAvailable,
  talkAvailable,
  chatAuthGateActive,
  talkCanPost,
  visibleIncomingCallId,
  radioAudioCueForEvent,
  playerStateRevision,
  publicTalkMessage,
  publicSearchAgentTimelineItems,
  materializedTalkMessagesForEvents,
  visibleTalkMessagesForState,
  publicPlayerState,
  contentByPublicId,
  contentByInternalId,
  observedAlbumMediaContentIds,
  talkByPublicId,
  talkByInternalId,
  appById,
  searchScenario,
  repairTarget,
  openTargetExists,
  notificationIdsForTarget,
} = defaultScenarioRuntime;
